import { cleanup, render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { ChatPanel } from "../components/ChatPanel";
import { result, source } from "./fixtures";

function setup(overrides: Partial<Parameters<typeof ChatPanel>[0]> = {}) {
  const props = {
    title: "Ward round" as string | null,
    results: [result(1), result(2)],
    hasOlder: false,
    loadingOlder: false,
    pending: null,
    canAsk: true,
    onAsk: vi.fn().mockResolvedValue(undefined),
    onLoadOlder: vi.fn().mockResolvedValue(undefined),
    onDeleteQuestion: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  };
  render(<ChatPanel {...props} />);
  return { props, user: userEvent.setup() };
}

describe("ChatPanel", () => {
  it("shows each question, answer, model and sources", async () => {
    const { user } = setup({
      results: [result(1, { sources: [source({ filename: "guide.pdf", page: 3, similarity: 0.5734 })] })],
    });
    expect(screen.getByText("Question 1?")).toBeInTheDocument();
    expect(screen.getByText("Answer 1.")).toBeInTheDocument();
    expect(screen.getByText("gemini:gemini-3.8-flash")).toBeInTheDocument();

    await user.click(screen.getByText("1 source"));
    expect(screen.getByText("guide.pdf")).toBeVisible();
    expect(screen.getByText(/page 3/)).toBeVisible();
    expect(screen.getByText(/similarity 0\.573/)).toBeVisible();
  });

  it("explains answers that were not generated by an LLM", () => {
    setup({ results: [result(1, { llm: "similarity_cutoff" }), result(2, { llm: "retrieval_only" })] });
    expect(screen.getByText("no relevant passage found (LLM not called)")).toBeInTheDocument();
    expect(screen.getByText("retrieval only (no LLM)")).toBeInTheDocument();
  });

  it("submits with Enter and clears the box; Shift+Enter adds a new line", async () => {
    const { props, user } = setup();
    const box = screen.getByRole("textbox", { name: "Question" });
    await user.type(box, "First line{Shift>}{Enter}{/Shift}second line");
    expect(props.onAsk).not.toHaveBeenCalled();
    await user.type(box, "{Enter}");
    expect(props.onAsk).toHaveBeenCalledWith("First line\nsecond line");
    expect(box).toHaveValue("");
  });

  it("disables asking until a document is ready", () => {
    setup({ canAsk: false });
    expect(screen.getByRole("textbox", { name: "Question" })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Ask" })).toBeDisabled();
  });

  it("shows a streaming answer with its sources and blocks a second question", () => {
    setup({ pending: { question: "Streaming?", answer: "Partial ans", sources: [source(), source({ source_id: 2 })] } });
    const live = screen.getByText("Streaming?").closest(".exchange") as HTMLElement;
    expect(within(live).getByText("Partial ans")).toHaveClass("streaming");
    expect(within(live).getByText("2 sources")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Ask" })).toBeDisabled();
  });

  it("says it is searching before any sources arrive", () => {
    setup({ pending: { question: "Q?", answer: "", sources: [] } });
    expect(screen.getByText("Searching documents…")).toBeInTheDocument();
  });

  it("loads earlier questions on request", async () => {
    const { props, user } = setup({ hasOlder: true });
    await user.click(screen.getByRole("button", { name: "Load earlier questions" }));
    expect(props.onLoadOlder).toHaveBeenCalledOnce();
  });

  it("hides the load button when everything is loaded", () => {
    setup({ hasOlder: false });
    expect(screen.queryByRole("button", { name: "Load earlier questions" })).not.toBeInTheDocument();
  });

  it("deletes a single question", async () => {
    const { props, user } = setup();
    await user.click(screen.getByRole("button", { name: "Delete question: Question 2?" }));
    expect(props.onDeleteQuestion).toHaveBeenCalledWith(result(2));
  });

  it("shows the chat's title, or 'New chat' before the first question", () => {
    setup({ title: "Ward round" });
    expect(screen.getByRole("heading", { name: "Ward round" })).toBeInTheDocument();
    cleanup();
    setup({ title: null, results: [] });
    expect(screen.getByRole("heading", { name: "New chat" })).toBeInTheDocument();
    expect(screen.getByText("Ask about your documents")).toBeInTheDocument();
  });

  it("blocks new questions while an answer is generated in another chat", async () => {
    const { props, user } = setup({ pending: null, busy: true });
    await user.type(screen.getByRole("textbox", { name: "Question" }), "Next question{Enter}");
    expect(screen.getByRole("button", { name: "Ask" })).toBeDisabled();
    expect(props.onAsk).not.toHaveBeenCalled();
  });
});
